### ISSUE TITLE
Champion should not be hovered instantly, There needs to be a way to lock in x time after the phase starts

### ISSUE THREAD

**Issue by BSweet16** [sweetriverfish/LeagueAutoAccept#11]
1. Even with a delay entered, the program selects the champion before the loading animation for champ select finishes. In other words, it should not even be possible to pick a champion yet, so it appears very suspicious.
2. Whenever there is a delay entered, the champion ban is selected, but not locked in during the appropriate time to ban a champion.

**Comment by sweetriverfish** [comment]
- The delay is only affecting lock in delay. You set the timer before your phase expires. The delay only exists so you are not forced to dodge due to not locking in.
- Yes, it does hover a champion before you are actually able to. It has never bothered me and for now that is the intended behavior. (I agree though, it should probably be fixed)
- If you want to instantly ban or lock picks, you should probably just set the instalock setting to true.
- The reason it might look like it doesn't ban/lock pick at the appropriate time is because league timer actually lies to you. Blind pick for example which has 90 seconds to pick actually has 93. It's the reason you can stay on 0 for a few seconds and not be forced to dodge in draft

To be honest I'm a little confused about what issues you are talking about. The only issue I see here is that it hovers a champion before you are actually able to.

**Comment by sweetriverfish** [comment]
I've made a new release which will wait 10 seconds before hovering a champion in draft pick. Let me know if this can be closed.

**Comment by BSweet16** [comment]
The other issue I mentioned is that it hovers, but does not lock in if you are using a delay

**Comment by BSweet16** [comment]
![image](https://user-images.githubusercontent.com/4945606/236703650-332dae8e-913d-43dc-81cd-84b47d7f4f54.png)
![image](https://user-images.githubusercontent.com/4945606/236703663-766970f5-7ee9-42e3-99ce-c50beec096cb.png)
Without input, I get stuck on this when it is my turn to lock in.

**Comment by sweetriverfish** [comment]
Are you saying it forces you to dodge?
By default, it should lock in 1500 ms before your phase is over (the in game timer should be at 0)

**Comment by BSweet16** [comment]
It will dodge if I do not intervene by clicking to lock in manually, yes. I still have the ability to lock in by clicking the button, but when using instalock feature in the AutoAccept, the "Lock In" and "Ban" buttons are selected by default. I would expect the  "Lock In" and "Ban" options to select itself via the script when using the delay as well.

**Comment by sweetriverfish** [comment]
Are you sure? Did you actually trust it enough to see if it locks in when the timer reaches the end?
I'm a little confused by what you mean with the second part of what you just said but the lock in works fine for me.
The delay works fine as well, I think?

https://github.com/sweetriverfish/LeagueAutoAccept/assets/13397494/8e8bd702-9811-4a9f-bd2c-578eb4aeb442

First part is blind pick with instalock enabled, second part is draft pick with instalock disabled. It locks in both times. I have used this many times when leaving the computer while in champ select and had no issues with it.

**Comment by BSweet16** [comment]
Ok I have just waited for the lock-in and ban phase to complete and it does indeed select champ and ban correctly. 

I would probably update this issue to include the fact that the timer to
lock in champion and ban selection should = "load in animation timer" + selected delay

**Comment by sweetriverfish** [comment]
The delay is made to allow you to pick how much time should be left before your phase ends, so that you are not forced to dodge. 

I'm not sure what `"load in animation timer" + selected delay` means but if you wanna flip the way the delay works so that it locks after x time after your phase starts, that's not going to work.

**Comment by BSweet16** [comment]
That is typically what a "delay" is. That is counter intuitive

**Comment by sweetriverfish** [comment]
Both of those are a delay. The reason I implemented it the way I did was because it was already locking in x time before your phase is over and I just wanted a way to customize it. 
I also still think it makes no sense to implement it like that because different queues have a different pick timer. If you set it to 60 for example so it locks late in blind it will never lock in draft because over there you've only got 30 seconds to lock in.
If I have the time and will to do so, I might implement a bunch of new delay options, and create a whole window full of random delay settings, but for now I'll leave it as is.

**Comment by BSweet16** [comment]
If you change it, I would recommend finding a way to have the delay start when the player is able to lock-in. If they enter a 5 second delay, then their champion would be locked in 5 seconds after their phase started.

**Comment by sweetriverfish** [comment]
I would just like to mention that I left it open because I do plan on implementing a delays settings at some point, I'm just being lazy and indefinitely postponing almost anything related to this project right now.

**Comment by BSweet16** [comment]
Oh, sorry I will reopen!

**Comment by sweetriverfish** [comment]
Done, will be released with the next update.
