### ISSUE TITLE
Add guide for how to use the software

### ISSUE THREAD

**Issue by AkseliLaakso** [sweetriverfish/LeagueAutoAccept#14]
I have tried to get the .exe to work but I don't understand how to use it correctly, atm I am stuck in a screen with "Getting summoner ID..." and I have no idea how to give it. So if possible could the "Read me" or something similar have a short guide for the software and how to use it. Thank you for creating this amazing software!

**Comment by sweetriverfish** [comment]
You're not supposed to do anything during that. It's supposed to be automatic and almost instant.

I'm thinking about it but I can't figure a reason for it to be stuck there. If I create some test builds, could you run them and report the results?

**Comment by AkseliLaakso** [comment]
Yeah, gladly!

**Comment by AkseliLaakso** [comment]
I am not the most experienced with github, so when you have the test builds ready, just tell me where I can download them. 😄

**Comment by sweetriverfish** [comment]
I will comment here and attach it probably. I currently don't have much time for that and will probably do it over the weekend if I don't get too lazy.

**Comment by sweetriverfish** [comment]
On a second thought, my idea was to log stuff but it will probably some sensitive information about your account. Would it be possible to communicate privately somehow?

Otherwise, if you have a throwaway account, could you open a cmd console and run some command?
Open task manager > details tab > find `LeagueClientUx.exe` > note the PID > run the following command the with your PID?
`wmic process where 'Processid=12316' get Commandline`
Copy paste the entire output (CTRL+A > CTRL+C) and paste it. I think it might be failing to process that data.

**Comment by AkseliLaakso** [comment]
I do have a discord (axel_valley) if that can be counted as private communication, but my English is not the best, so I might be a bit unclear. I do have a "smurf" account I guess (throwaway account), so I might try to run the command.

**Comment by AkseliLaakso** [comment]
I ran the command, do you want me to paste the output here or in a private chat, also you mentioned that there might be some sensitive information, is there any way to avoid that?

**Comment by sweetriverfish** [comment]
(issue addressed via pms)
For those who wonder: the issue was that he had strict UAC settings that did not allow wmic to properly run unless the app was started with administrator privileges.
