### ISSUE TITLE
[Suggestion] The ability to insta write something in the chat

### ISSUE THREAD

**Issue by Neinndall** [sweetriverfish/LeagueAutoAccept#2]
Hello! This would be very nice and it is, adding the ability to add what I would type in chat once I enter the champ selection.

For example: Instant Message: Mid
When the queue is accepted, it will immediately write what I put in earlier.

regards,

**Comment by sweetriverfish** [comment]
I was thinking about it when creating it but I couldn't figure out how to create a "ui" for it so I skipped it.
I will probably add it at some point when I feel like working on it again, it just didn't feel necessary when creating the app because instalocking champions in blind picks wasn't the goal of it

**Comment by Neinndall** [comment]
The thing that is a super useful tool for blind picks for new champion release days. I decided to use this one because the interface is simpler and I thought that something is missing, the idea that I proposed to you!

**Comment by SabDabz86** [comment]
Yes that would be a great addition to the app it works so great just calling the lanes would be awesome for blind pick !

**Comment by sweetriverfish** [comment]
A year late, maybe, but it has been added it in the latest version.
